### ISSUE TITLE
readme should state this is for *univariate* polynomials only

### ISSUE THREAD

**Issue by chriscoey** [giordano/PolynomialRoots.jl#5]
It wasn't obvious to me from the readme that this package cannot handle multivariate polynomials

**Comment by giordano** [comment]
The `README.md` has a few examples, all of them for univariate polynomials only.  The `README.md` also refers to the paper where the algorithm is introduced, where you could have found that it's for univariate polynomials, just like the `zroots` routine from Numerical Recipes (mentioned in the `README.md` as well).

Furthermore, the documentation also clearly states that the argument is the *vector* of coefficients in ascending order, it's not clear to me how you'd expect this to work for multivariate polynomials.

Anyway, I explicitly mentioned *univariate* in the `README.md` to avoid any confusion.
