### ISSUE TITLE
PolynomialRoots Not found in Julia 1.0.1

### ISSUE THREAD

**Issue by mattcbro** [giordano/PolynomialRoots.jl#8]
I'm not sure why but this package does not seem to be in the registery.

```
julia> Pkg.add("PolynomialRoots")
  Updating registry at `~/programs/JuliaPro-1.0.1.1/JuliaPro/pkgs-1.0.1.1/registries/JuliaPro`
  Updating git-repo `https://pkg.juliacomputing.com/registry/JuliaPro`
ERROR: The following package names could not be resolved:
 * PolynomialRoots (not found in project, manifest or registry)
Please specify by known `name=uuid`.
```
I can still import it in julia 0.6.4 though.

**Comment by giordano** [comment]
You're using JuliaPro, I know that its registry is not the same as the General registry used by "regular" Julia, see https://discourse.julialang.org/t/physicalconstants-package-with-julia-1-0-1-1/16189

**Comment by mattcbro** [comment]
> You're using JuliaPro, I know that its registry is not the same as the General registry used by "regular" Julia, see https://discourse.julialang.org/t/physicalconstants-package-with-julia-1-0-1-1/16189

Yeah I finally figured that out the hard way.  Sorry for spamming this spurious issue.  It does appear to load in the vanilla 1.0.1.

**Comment by giordano** [comment]
No problem :wink:
